version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=YummyTime
      - MYSQL_USER=yummytime
      - MYSQL_PASSWORD=yummytime123
    ports:
      - 4192:3306
  app:
    build:
      context: ./YummyTimeWeb
    ports:
      - 4190:8080
      - 4191:9990
      - 4200:8787
    depends_on:
      - db
    links:
      - db
    dns: 8.8.8.8
